name: Campusaachen66
analytics: {}
purpose:
  - type: contact
    url: 'mailto:campusaachen22@icloud.com'
    label: Contact me
  - type: contact
    url: 'tel:+31647178084'
    label: Call +31 6 47 17 80 84
github: true
description: 'Surfing for Life '
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F1oJ04RovaGg%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D1oJ04RovaGg&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F1oJ04RovaGg%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Visit Portugal
          url: 'https://www.youtube.com/user/VisitPortugal'
          avatar: {}
      '@context': 'http://schema.org'
      keywords:
        - visitportugal
        - portugal
        - tourism
        - holiday
        - vacation
        - holidays
        - vacations
        - europe
        - europa
        - travel
        - trip
        - destination
        - tourist
        - traveling
        - travelling
        - travels
        - ...
      '@type': VideoObject
      title: Can't Skip Freedom
      isBasedOnUrl: 'https://www.youtube.com/watch?v=1oJ04RovaGg'
      publisher:
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        url: 'https://www.youtube.com/'
        name: YouTube
        domain: www.youtube.com
      app_links:
        - app_store_id: '544007664'
          namespace: ai
          app_name: YouTube
          url: 'vnd.youtube://www.youtube.com/watch?v=1oJ04RovaGg&feature=applinks'
          type: ios
        - package: com.google.android.youtube
          app_name: YouTube
          namespace: ai
          url: 'vnd.youtube://www.youtube.com/watch?v=1oJ04RovaGg&feature=applinks'
          type: android
        - url: 'https://www.youtube.com/watch?v=1oJ04RovaGg&feature=applinks'
          type: web
          namespace: ai
        - id: '544007664'
          namespace: twitter
          url: 'vnd.youtube://www.youtube.com/watch?v=1oJ04RovaGg&feature=applinks'
          type: ipad
          name: YouTube
        - id: '544007664'
          namespace: twitter
          url: 'vnd.youtube://www.youtube.com/watch?v=1oJ04RovaGg&feature=applinks'
          type: iphone
          name: YouTube
        - id: com.google.android.youtube
          namespace: twitter
          url: 'https://www.youtube.com/watch?v=1oJ04RovaGg'
          type: googleplay
          name: YouTube
        - path: http/www.youtube.com/watch?v=1oJ04RovaGg
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=1oJ04RovaGg
          package: '544007664'
          namespace: google
          type: ios
      related: []
      description: >-
        Jack is a man who thinks life is slipping through his fingers. He can
        hardly breathe, he feels overwhelmed by his daily routine. He sets off
        to see a new world, to get lost amidst the light that a new place
        brings. Can't skip freedom. Can't skip youth. Can't skip life.
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - id: 0c6487f9-b032-4950-8adf-13de64924569
    name: Booking Price
    type: content
  - id: 49a3e47d-2f0d-49cc-8343-82b1b07370c6
    name: Lessons
    type: content
  - id: 29d58fd4-d4cc-4ae3-8a3b-74cd0e8b5ba4
    name: Accommodation
    type: content
  - id: 5ce86cb1-a167-4710-9df2-c2a461114f4c
    name: Surf
    type: content
  - id: 9a8f039e-995e-4b10-a393-e98f9bb7fc76
    name: Kitesurf
    type: content
  - id: 68572459-0f74-40af-bd37-e0278f0e23fa
    name: Multi Sport
    type: content
  - id: 13cc4f66-ee1f-4bff-b3ca-d89f01b15c56
    name: Surf & yoga
    type: content
layout_spectrum: 0.11091360852186855
color:
  lightness: 0.1445904007643498
  brandColors:
    - '#04BFBF'
    - '#CAFCD8'
    - '#F7E967'
    - '#A9CF54'
    - '#588F27'
  saturation: 0.15129857398385163
  brandStrength: 0.2360999912836838
  rhythmicContrast: 0.6610509003912753
content_rating:
  adult: false
typography_spectrum: 0.6546788337248571
opengraph: {}
title: 'Campusaachen Portugal '
